hydra:
  run:
    # dir: <path>/${model.name}/${now:%Y-%m-%d_%H%M%S}
     dir: C:/Users/Ashley/CSCI5561/deep_ev_tracker/models/klt_orb/${now:%Y-%m-%d_%H%M%S}

# gt_path: <path>/gt_tracks
gt_path: C:/Users/Ashley/CSCI5561/deep_ev_tracker/gt_tracks/klt_orb
running_locally: False


# weights_path: <path>
weights_path: C:/Users/Ashley/CSCI5561/deep_ev_tracker/new_multiflow_weights/weights_finetuned_ec.ckpt
# weights_path: C:/Users/Ashley/CSCI5561/deep_ev_tracker/p_weights/weights_finetuned_ec.ckpt

track_name: shitomasi_custom
representation: time_surfaces_v2_5
patch_size: 31
visualize: True
dt_track_vis: 0.2

# Composing nested config with default
defaults:
  - model: correlation3_unscaled
# Pytorch lightning trainer's argument
trainer:
  gpus: [0]
